### ISSUE TITLE
ssl cert generation tips

### ISSUE THREAD

**Issue by JoshData** [vzvenyach/nginx-ssl#2]
You can skip generating the private key with a password, since you're going to store it without a password anyway.

For the CSR, only the C and CN fields are needed. There's no need to have it ask the user for anything else. Maybe you need to add `< /dev/null` to prevent it from asking more questions.

see:
https://github.com/mail-in-a-box/mailinabox/blob/master/setup/ssl.sh

**Comment by JoshData** [comment]
Oh I see you use the password-protected key. Does nginx ask for a password each time you start it?

**Comment by vzvenyach** [comment]
I think I turned off the password protection. I'll look into the decrypt step...

**Comment by vzvenyach** [comment]
And thanks re the tip about the CSR details!

**Comment by vzvenyach** [comment]
I integrated these suggestions yesterday. Thanks @JoshData!
